spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/auth
    username: postgres
    password: docker@1993#

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        enable_lazy_load_no_trans: true

jwt:
  secret: f602da1a7deb2e5b23169f47d6d294cfcbb0fcc472ab3f361ee2792f9378ca2